### ISSUE TITLE
 `slice` method

### ISSUE THREAD

**Issue by zackarno** [r-tidy-remote-sensing/tidyrgee#1]
Just had a thought that in addition to `filter` , `group_by`, `summarise`  we might as well include a `slice` method for `ImageCollection`s . 

This would allow the user to select images from an imageCollection by index. If we want the first 3 images from a collection (`ic`)  it would just be:

```
ic %>%
  slice(1:3)
```

Heres a list of our method ideas so far

- [x] filter - should cover `filterDate` and also allow filtering by metadata/properties
- [x] group_by - basically when the `ImageCollection` methods for `group_by` are combined with `filter` they equal `filterCalendarRange`
- [x] summarise - compositing images, applying the pixel-level stats
- [x] **slice** - easy selection of images from imageCollections by index

**Comment by zackarno** [comment]
adding more suggested method ideas here for now (thanks @joshualerickson ) 

- [ ] select - select bands
- [ ] rename - rename bands/props

**Comment by zackarno** [comment]
`slice` method added for tidyee... leaving it open as I have not yet added for `ee.imagecollection.ImageCollection`. I think this is an instance where I can easily add an imageCollection method which does not rely on `as_tidyee()` running in the background... would be cool to have some of these so we can try to shift in that direction for imageCollection methods eventually. The `as_tidyee()` in the background for ic methods is fine, its just slower so I could see some people liking the ic methods that don't need it (although in some cases this is drastically harder to write...i.e filter)

**Comment by joshualerickson** [comment]
rgeeExtra uses generics for '[' operators to *slice*-ish the ic. Could use their framework/package or adapt more into `slice` style?

**Comment by zackarno** [comment]
I remember seeing `[` and `[[` in {rgeeExtra}, but it looks like they might be using it more for `selecting` /`subsetting` bands from an  `img` or `ic` ? is that right? looking over it now it looks like they might have something similar to our new `slice` which is `ee_get`?

Either way iit'd be cool to adopt `[`/`[[` to align with them. I kind of like our `dplyr-like` `slice` equivalent though for chopping up ics base on index. 

lmk

**Comment by zackarno** [comment]
going to close this since we have implemented the `slice()` functionality. We can continue comms on additional new `dplyr` equivalent functions in a Discussion thread.
