### ISSUE TITLE
Naming issue 

### ISSUE THREAD

**Issue by mhkhan27** [r-tidy-remote-sensing/tidyrgee#31]
Hey, first of all, thanks for the great work. **Tidyrgee is working like a wizard.** I just wanted to flag two issues - 

1. I am not sure if it's only me, but while calculating the StdDev, it seems in the tidy object it creates a band, namely "XXX_sd" but for further calculation, I always have to use "XXX_stdDev"! Might be an issue! 

2. Secondly, I got confused by the function name "inner_join" as it's the same as dplyr::inner_join. I think it would be great to rethink the function name. (Perhaps join_bands_by() ?)

**Comment by zackarno** [comment]
Hey @mhkhan27 , glad tidyrgee has been working for you  :-) . 

I think you are right on both issues.

1.  I'll try to adjust the summary methods so the "XXX_**sd**" name sticks and does not convert back to "XXX_stdDev".
2.  yeah i think `inner_join()` is probably not the best name for this function. We were trying to stick to `dplyr` verbs, but i think it might be confusing in this case since we are just really joing bands from based on a shared property. So i think `join_bands_by` like you suggested, or maybe just `join_bands` with a `by` argument might might help avoid confusion -  what do you think @joshualerickson ?

**Comment by joshualerickson** [comment]
Hey @mhkhan27 , glad your are liking it as well! Thanks for the issue and suggestion on the name change :)

Sounds good on tracking down the loss of 'sd' during further calculations! Zach or @mhkhan27 if you can flag it in a PR then we can put it into the tests as well. I'm still on the fence with the name change for `inner_join()`. Here's why:  

1. The function is doing an `inner_join` with the image collections, right?, e.g. ic$join$inner().
2. If keeping the package within the tidy-methods framework, then how much deviance do we want? I think it's fine for a few little things for sure! But, this brings up the 'is it `tidyrgee` or `easyrgee`' decision we've talked about earlier.  You can always adapt and change so don't let me dissuade you from changing the name but I'd suggest keeping exported functions in `tidyrgee` similar to the tidy-framework naming scheme and moving on to `easyrgee` for higher-level function names like `join_bands_by()`, etc. 

Again, not my call and it wouldn't bother me if we did change the name! Just throwing it out there :)

**Comment by zackarno** [comment]
Thanks @joshualerickson - good points, now I am also on the fence. I just opened a "Discussion" where we can continue the chat on `inner_join()` vs `join_by(by="band)` as well as other naming issues related to using tidyverse/dplyr verbs: https://github.com/r-tidy-remote-sensing/tidyrgee/discussions/32

 I think after fixing the first `sd` vs `stdDev` problem @mhkhan27 pointed out we can close this issue and carry on the function naming discussion there. Hopefully the new "discussion" board will be useful for making smart decision on other naming conventions as well.

**Comment by zackarno** [comment]
> Hey, first of all, thanks for the great work. **Tidyrgee is working like a wizard.** I just wanted to flag two issues -
> 
> 1. I am not sure if it's only me, but while calculating the StdDev, it seems in the tidy object it creates a band, namely "XXX_sd" but for further calculation, I always have to use "XXX_stdDev"! Might be an issue!
> 2. Secondly, I got confused by the function name "inner_join" as it's the same as dplyr::inner_join. I think it would be great to rethink the function name. (Perhaps join_bands_by() ?)

@mhkhan27  - the 'stdDev` vs `sd` issue should be fixed in the latest. Now after running a standard deviation reducer the default band suffix is `_sd` in all components of the tidyee object. Will continue the naming discussion in a separate thread
